apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-api
  template:
    metadata:
      labels:
        app: ecommerce-api
    spec:
      containers:
        - name: ecommerce-api
          image: badzboss/ecommerce-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-api-config
                  key: PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-api-secret
                  key: JWT_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-api-secret
                  key: JWT_ISSUER
            - name: JWT_EXPIRE_HOURS
              valueFrom:
                secretKeyRef:
                  name: ecommerce-api-secret
                  key: JWT_EXPIRE_HOURS
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-api-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-api-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-api-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-api-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-api-secret
                  key: DB_NAME
            - name: DB_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-api-config
                  key: DB_SSLMODE
            - name: REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-api-config
                  key: REDIS_ADDR
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-api-config
                  key: REDIS_PASSWORD
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-api-config
                  key: REDIS_DB
