apiVersion: v1
kind: Service
metadata:
  name: ecommerce-api-service
spec:
  type: NodePort
  selector:
    app: ecommerce-api
  ports:
    - port: 80
      targetPort: 8080 # ส่งต่อไปที่ 8080 ใน Pod
      nodePort: 30080 # Node รับที่ 30080
