apiVersion: v1
kind: Service
metadata:
  name: postgres-api-service
spec:
  type: NodePort
  selector:
    app: postgres-ecommerce-api
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30032
