apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-ecommerce-api
  template:
    metadata:
      labels:
        app: postgres-ecommerce-api
    spec:
      containers:
        - name: postgres-ecommerce-api
          image: postgres:16
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-ecommerce-api-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-ecommerce-api-configmap
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-ecommerce-api-configmap
                  key: POSTGRES_DB
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
