apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-ecommerce-api
  template:
    metadata:
      labels:
        app: redis-ecommerce-api
    spec:
      containers:
        - name: redis-api
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
